### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [JustinFincher/UniLWP.Droid.Package.Free#1]
HI @JustinFincher,

Thanks for making the great upm package free. I'm the creator of [OpenUPM](https://openupm.com) platform, an open-source UPM registry, and continuous build service based on Git tags. So far it is hosting more than 200+ UPM packages.

To make it happens, I would suggest you make GitHub releases (which create Git tags) for version control. It can be achieved either manually or using [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

Then you can submit your package here: https://openupm.com/packages/add/

**Comment by JustinFincher** [comment]
https://openupm.com/packages/com.justzht.unilwp.droid.free/  
Done! :-D

**Comment by favoyang** [comment]
Awesome! Feel free to add a badge and the installation guide ([an example](https://github.com/favoyang/unity-addressable-importer#install-via-openupm))

[![openupm](https://img.shields.io/npm/v/com.justzht.unilwp.droid.free?label=openupm&registry_uri=https://package.openupm.com)](https://openupm.com/packages/com.justzht.unilwp.droid.free/)
